config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users
  resources :jobs
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :job_provider, foreign_key: "id"
  has_and_belongs_to_many :job_seekers
end

app/models/job_provider.rb
class JobProvider < User
  has_many :jobs, foreign_key: "created_by"
end

app/models/job_seeker.rb
class JobSeeker < User
  has_and_belongs_to_many :jobs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :addresses, allow_destroy: true
  has_one_attached :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:type])
    devise_parameter_sanitizer.permit(:account_update,keys: [ :picture, addresses_attributes: [ :description, :_destroy, :id]])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
    @requirements = ['java', 'ruby', 'html', 'css']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
  def index
    if current_user.type == 'JobSeekeer'
      user_type = 'JobProvider'
    elsif current_user.type == 'JobProvider'
      user_type = 'JobSeeker'
    end
    @users = User.where(type: user_type)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/index.html.erb
<h4>All jobs</h4> <br>
<% if @jobs %>
  <% @jobs.each do |job| %>
    <%= job.title %>
  <% end %>
<% end %>

app/views/jobs/new.html.erb
<div class="col-sm-4">
  <%= form_for @job, html: {class: "form-group"} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
    <%= f.label :requirements %>
    <%= f.select :requirements, @requirements, class: "form-control" %> <br>
    <%= f.submit "Create" %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "#{current_user.type}", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav col-sm-8">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "JobSeekers", users_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="nav col-sm-4 navbar-nav justify-content-end pull-right">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Show", user_path(current_user.id), class: "dropdown-item"  %>
          <%= link_to "Sign Out",  destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/header' %>
    <%end%>
    <% if notice %>
      <p class="alert alert-success" role="alert" alert-dismissible fade show><%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger" role="alert" alert-dismissible fade show><%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h4>All Users </h4> <br>
<% if @users %>
  <% @users.each do |user| %>
    <%= user.email %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h4> Type </h4><%= current_user.type %><br>
<h4> email </h4><%= current_user.email %><br>
<h4> Address </h4>
<ul>
  <% current_user.addresses.each do |add| %>
    <li>
      <%= add.description %>
    </li>
  <% end %>
</ul>
<h4> Image </h4>
<span class="image"><%= image_tag current_user.picture,class: "img-fluid" %></span>

app/views/welcome/index.html.erb
<% if current_user.type == "JobProvider" %>
  <%= link_to "Create new job", new_job_path %>
<% end %>